### get EmployeeSet
GET http://localhost:4004/odata/v4/my-org/EmployeeSet

### get EmployeeSet with empid
GET http://localhost:4004/odata/v4/my-org/EmployeeSet(ID='emp1c240-5d9b-11ee-8c99-0242ac120001')


### get EmployeeSet with filter with dependents
GET http://localhost:4004/odata/v4/my-org/EmployeeSet('emp1c240-5d9b-11ee-8c99-0242ac120001')/dependents

### Post EMP
POST http://localhost:4004/odata/v4/my-org/EmployeeSet
Content-Type: application/json

{      
      "createdAt": "2025-10-19T10:30:00.000Z",
      "createdBy": "admin",
      "modifiedAt": "2025-10-19T11:00:00.000Z",
      "modifiedBy": "manager",
      "FirstName": "Sam",
      "Age":66,
      "LastName": "Jane",
      "Salary": 5000,
      "Role": "IT Engineer",            
      "yrsOfExperience": "10",
      "Address": "Dusky Lane",
      "Country_code": "US",
      "City": "Austin",
      "Department_ID": "d1c5a240-5d9c-11ee-8c99-0242ac120001",
      "FavProduct": "Chai"      
    }

### get Dependent of emp
GET http://localhost:4004/odata/v4/my-org/EmpDependentSet

### get one dependent
GET http://localhost:4004/odata/v4/my-org/EmpDependentSet('demp1c40-5d9b-11ee-8c99-0242ac120001')

### Get dependent for specific employee
GET http://localhost:4004/odata/v4/my-org/EmpDependentSet?filter=(OrgEmployee_ID eq 'emp1c240-5d9b-11ee-8c99-0242ac120001')

###CREATE DEPENDENT of employee
POST http://localhost:4004/odata/v4/my-org/EmpDependentSet
Content-Type: application/json

{
     "ID": "demp1c40-5d9b-11ee-8c99-0242ac120002",
      "createdAt": "2025-10-19T10:30:00.000Z",
      "createdBy": "admin",
      "modifiedAt": "2025-10-19T11:00:00.000Z",
      "modifiedBy": "manager",
      "DepdFirstName": "Kiara",
      "DepdLastName": "Amraotkar",
      "Depdage": "6",
      "relationship": "Daughter",
      "OrgEmployee_ID": "emp2e580-5d9b-11ee-8c99-0242ac120002"      
}

### get dept
GET http://localhost:4004/odata/v4/my-org/DepartmentSet

### get dept with key
GET http://localhost:4004/odata/v4/my-org/DepartmentSet('b5d1e365-7fb4-4967-85e5-167453fd59a2')


### Create dept
POST http://localhost:4004/odata/v4/my-org/DepartmentSet
Content-Type: application/json

{  
  "DepartName": "Sales Force",
  "DepartmentCode": "Sales Force",
  "AdminPWD": "Admin123"
}

### Update dept
PUT http://localhost:4004/odata/v4/my-org/DepartmentSet('253014a6-7850-4e8e-8d71-5c83848a0f4c')
Content-Type: application/json

{  
  "DepartName": "Sales Force 12",
  "DepartmentCode": "Sales Force 12",
  "AdminPWD": "Admin123"
}

### DELETE dept
DELETE  http://localhost:4004/odata/v4/my-org/DepartmentSet(ID='253014a6-7850-4e8e-8d71-5c83848a0f4c')
Content-Type: application/json
Slug: Admin123



### get files
GET http://localhost:4004/odata/v4/my-org/AttachmentSet


### post file
POST http://localhost:4004/odata/v4/my-org/AttachmentSet
Content-Type: application/json

{
     "mediaType": "pdf",
    "filename" : "sample.pdf",
    "EmployeeFile_ID": "emp1c240-5d9b-11ee-8c99-0242ac120001"
}


### put content
PUT http://localhost:4004/odata/v4/my-org/AttachmentSet('ff243c15-13a2-4a5a-8d3a-02c5a56b213e')/content
Content-Type: application/pdf

< ../sample.pdf

###get all attachment for employee
GET http://localhost:4004/odata/v4/my-org/EmployeeSet('emp1c240-5d9b-11ee-8c99-0242ac120001')/MediaDoc

### get expanded entity for dependeds 
GET http://localhost:4004/odata/v4/my-org/EmployeeSet?$expand=dependents

### get attachments with employee details
GET http://localhost:4004/odata/v4/my-org/EmployeeSet?$expand=MediaDoc

### get expanded entity for dependeds with attachemnts
GET http://localhost:4004/odata/v4/my-org/EmployeeSet?$expand=dependents,MediaDoc



### get expanded entity for dependeds with attachemnts for specific employee
GET http://localhost:4004/odata/v4/my-org/EmployeeSet('emp1c240-5d9b-11ee-8c99-0242ac120001')?$expand=dependents,MediaDoc


### send Mail
GET http://localhost:4004/odata/v4/my-org/sendEmail
Content-Type: application/json

{
  "ID": "emp1c240-5d9b-11ee-8c99-0242ac120001"
}
